=== fofanadonatien/PROJET_JEU_VIDEO_XML_CS/Test2/XSD/jeuXsd.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:se="https://github.com/team-phoenix/strange-expedition"
        targetNamespace="https://github.com/team-phoenix/strange-expedition"
        elementFormDefault="qualified">


    <element name="Jeu" type="se:Jeu"/>
    <complexType name="Jeu">
        <sequence>
            <element name="nomJeu" type="string"/>
            <element name="fondImage" type="string"/>
            <element name="joueur" type="se:Joueur"/>
            <element name="sauvegarde" type="se:sauvegarde" minOccurs="0"/>
            <element name="map" type="se:Map"/>
            <element name="score" type="se:TypeScore"/>
        </sequence>
    </complexType>

    <complexType name="Joueur">
        <sequence>
            <element name="nom" type="se:NomJoueur"/>
            <element name="vie" type="se:TypeVie"/>
            <element name="inventaire" type="se:TypeInventaire"/>
        </sequence>
    </complexType>
    <complexType name="Map">
        <sequence>
            <element name="donjon" type="se:Donjons"/>
            <element name="fondImage" type="string"/>
            <element name="objet" type="se:Objets" maxOccurs="unbounded"/>
            <element name="pnj" type="se:PNJ" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="TypeInventaire">
        <sequence>
            <element name="piece" type="int" minOccurs="0" maxOccurs="unbounded"/>
            <element name="objet" type="se:Objets" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Donjons">
        <choice>
            <element name="donjonDevinette" type="se:DonjonDevinette"/>
            <element name="donjonZombie" type="se:DonjonZombie"/>
        </choice>
    </complexType>
    <complexType name="PNJ">
        <choice>
            <element name="sorcierPnj" type="se:SorcierPNJ"/>
            <element name="zombiePnj" type="se:ZombiePNJ"/>
        </choice>
    </complexType>
    <complexType name="sauvegarde">
        <sequence>
            <element name="nom" type="se:NomJoueur"/>
            <element name="vie" type="se:TypeVie"/>
            <element name="inventaire" type="se:TypeInventaire"/>
            <element name="donjon" type="se:Donjons"/>
        </sequence>
    </complexType>
    <complexType name="Objets">
        <sequence>
            <element name="arme" type="se:Armes"/>
            <element name="consommable" type="se:Consommables"/>
        </sequence>
    </complexType>
    <complexType name="DonjonDevinette">
        <sequence>
            <element name="decor" type="string" minOccurs="0"/>
            <element name="difficulte" type="se:TypeDifficulte"/>
            <element name="question" type="se:Questions" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="DonjonZombie">
        <sequence>
            <element name="decor" type="string" minOccurs="0"/>
            <element name="difficulte" type="se:TypeDifficulte"/>
        </sequence>
    </complexType>
    <complexType name="SorcierPNJ">
        <sequence>
            <element name="nom" type="string"/>
            <element name="role" type="string"/>
            <element name="dialogue" type="string"/>
        </sequence>
    </complexType>
    <complexType name="ZombiePNJ">
        <sequence>
            <element name="nom" type="string"/>
            <element name="role" type="string"/>
            <element name="dialogue" type="string"/>
            <element name="PointVie" type="int"/>
            <element name="degats" type="se:TypeDegats"/>
        </sequence>
    </complexType>
    <complexType name="Armes">
        <sequence>
            <element name="nom" type="string"/>
            <element name="description" type="string"/>
            <element name="degats" type="se:TypeDegats"/>
        </sequence>
    </complexType>
    <complexType name="Consommables">
        <sequence>
            <element name="nom" type="string"/>
            <element name="description" type="string"/>
            <element name="effet" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Questions">
        <sequence>
            <element name="texte" type="string"/>
            <element name="propositions" type="se:ListePropositions"/>
            <element name="bonneReponse" type="string"/>
            <element name="mauvaiseReponse" type="string"/>
        </sequence>
    </complexType>
    <complexType name="ListePropositions">
        <sequence>
            <element name="Proposition" type="string" maxOccurs="4"/>
        </sequence>
    </complexType>
    <!-- Nom du joueur : 4 lettres + 2 chiffres (LéoP12) -->
    <simpleType name="NomJoueur">
        <restriction base="string">
            <pattern value="[A-Za-zÀ-ÿ]{4}[0-9]{2}"/>
        </restriction>
    </simpleType>

    <simpleType name="TypeVie">
        <restriction base="int">
            <minInclusive value="100"/>
            <maxInclusive value="200"/>
        </restriction>
    </simpleType>

    <simpleType name="TypeDegats">
        <restriction base="int">
            <minInclusive value="25"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="TypeDifficulte">
        <restriction base="int">
            <minInclusive value="1"/>
            <maxInclusive value="5"/>
        </restriction>
    </simpleType>


    <simpleType name="TypeScore">
        <restriction base="int">
            <minInclusive value="0"/>
            <maxInclusive value="9999"/>
        </restriction>
    </simpleType>
</schema>

=== fofanadonatien/PROJET_JEU_VIDEO_XML_CS/Test2/XML/XmlJeu.xml
<Jeu xmlns="https://github.com/team-phoenix/strange-expedition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/team-phoenix/strange-expedition ../xsd/jeuXsd.xsd">
    <nomJeu>Strange Expedition</nomJeu>
    <fondImage>images/fond_temple_xml.png</fondImage>
    <joueur>
        <nom>LéoP12</nom>
        <vie>150</vie>
        <inventaire>
            <piece>0</piece>
        </inventaire>
    </joueur>
    <map>
        <donjon>
            <donjonDevinette>
                <decor>lieux/auberge.jpg</decor>
                <difficulte>1</difficulte>
                <!--  questions  -->
                <question>
                    <texte>Que signifie l'acronyme XML ?</texte>
                    <propositions>
                        <Proposition> 1 - Extensible Markup Language (W)</Proposition>
                        <Proposition> 2 - Example Markup List (X)</Proposition>
                        <Proposition> 3 - Extra Modern Language (C)</Proposition>
                        <Proposition> 4 - Extended Meta Logic (V)</Proposition>
                    </propositions>
                    <bonneReponse>W</bonneReponse>
                    <mauvaiseReponse>XCV</mauvaiseReponse>
                </question>
                <question>
                    <texte>Quel est le role d'un schema XSD ?</texte>
                    <propositions>
                        <Proposition> 1 - Decrire la structure et les types de donnees d'un document XML (W)</Proposition>
                        <Proposition> 2 - Afficher le contenu XML dans un navigateur (X)</Proposition>
                        <Proposition> 3 - Convertir XML en JSON (C)</Proposition>
                        <Proposition> 4 - Verifier les balises HTML (V)</Proposition>
                    </propositions>
                    <bonneReponse>W</bonneReponse>
                    <mauvaiseReponse>XCV</mauvaiseReponse>
                </question>
                <question>
                    <texte>Quelle instruction permet de relier un XML a un schema XSD ?</texte>
                    <propositions>
                        <Proposition> 1 - xsd:link (W)</Proposition>
                        <Proposition> 2 - xsi:schemaLocation (X)</Proposition>
                        <Proposition> 3 - xmlns:xsd (C)</Proposition>
                        <Proposition> 4 - xml:schemaRef (V)</Proposition>
                    </propositions>
                    <bonneReponse>X</bonneReponse>
                    <mauvaiseReponse>WCV</mauvaiseReponse>
                </question>
            </donjonDevinette>
        </donjon>
        <fondImage>images/carte_donjon_xml.png</fondImage>
        <objet>
            <arme>
                <nom>Plume du Sage</nom>
                <description>Un artefact magique permettant de taper plus fort</description>
                <degats>25</degats>
            </arme>
            <consommable>
                <nom>Potion de Savoir</nom>
                <description>Améliore temporairement la compréhension des ennemis et donc </description>
                <effet>+5 classe Armure</effet>
            </consommable>
        </objet>
        <pnj>
            <sorcierPnj>
                <nom>Archivus</nom>
                <role>Sorcier</role>
                <dialogue>Bienvenue, jeune apprenti ! Réponds correctement à mes devinettes sur XML pour avancer dans ton apprentissage.</dialogue>
            </sorcierPnj>
        </pnj>
    </map>
    <score>0</score>
</Jeu>
